// <auto-generated />
using System;
using AccountingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311081429_DatabaseCreate")]
    partial class DatabaseCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingSystem.Data.Account_List", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountingSystem.Data.Group_List", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AccountingSystem.Data.Journal_Entry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("AccGrpId")
                        .HasColumnType("integer");

                    b.Property<int>("AccNameId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("credit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("date");

                    b.Property<decimal?>("debit")
                        .HasColumnType("numeric");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("AccGrpId");

                    b.HasIndex("AccNameId");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("AccountingSystem.Data.Journal_Entry", b =>
                {
                    b.HasOne("AccountingSystem.Data.Group_List", "AccGrp")
                        .WithMany("Journal_Entries")
                        .HasForeignKey("AccGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingSystem.Data.Account_List", "AccName")
                        .WithMany("Journal_Entries")
                        .HasForeignKey("AccNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccGrp");

                    b.Navigation("AccName");
                });

            modelBuilder.Entity("AccountingSystem.Data.Account_List", b =>
                {
                    b.Navigation("Journal_Entries");
                });

            modelBuilder.Entity("AccountingSystem.Data.Group_List", b =>
                {
                    b.Navigation("Journal_Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
