// <auto-generated />
using System;
using AccountingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250302122321_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingSystem.Data.Account_List", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("accountId"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("accountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountingSystem.Data.Amount", b =>
                {
                    b.Property<int>("amountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("amountId"));

                    b.Property<int?>("creditId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.Property<int?>("debitId")
                        .HasColumnType("integer");

                    b.HasKey("amountId");

                    b.HasIndex("creditId");

                    b.HasIndex("debitId");

                    b.ToTable("Amounts");
                });

            modelBuilder.Entity("AccountingSystem.Data.Credited_Accounts", b =>
                {
                    b.Property<int>("creditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("creditId"));

                    b.Property<int?>("accountId")
                        .HasColumnType("integer");

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.HasKey("creditId");

                    b.HasIndex("accountId");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("AccountingSystem.Data.Debit_Accounts", b =>
                {
                    b.Property<int>("debitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("debitId"));

                    b.Property<int?>("accountId")
                        .HasColumnType("integer");

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("debitId");

                    b.HasIndex("accountId");

                    b.ToTable("Debit");
                });

            modelBuilder.Entity("AccountingSystem.Data.Group_List", b =>
                {
                    b.Property<int>("groupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("groupId"));

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("groupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AccountingSystem.Data.Journal_Entry", b =>
                {
                    b.Property<int>("journal_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("journal_code"));

                    b.Property<int?>("accountId")
                        .HasColumnType("integer");

                    b.Property<int?>("creditId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.Property<int?>("debitId")
                        .HasColumnType("integer");

                    b.HasKey("journal_code");

                    b.HasIndex("accountId");

                    b.HasIndex("creditId");

                    b.HasIndex("debitId");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("AccountingSystem.Data.Trial_Balance", b =>
                {
                    b.Property<int>("balance_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("balance_Id"));

                    b.Property<int?>("accountId")
                        .HasColumnType("integer");

                    b.Property<int?>("amountId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("datetime")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("groupId")
                        .HasColumnType("integer");

                    b.HasKey("balance_Id");

                    b.HasIndex("accountId");

                    b.HasIndex("amountId");

                    b.HasIndex("groupId");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("AccountingSystem.Data.Amount", b =>
                {
                    b.HasOne("AccountingSystem.Data.Credited_Accounts", "Credit")
                        .WithMany()
                        .HasForeignKey("creditId");

                    b.HasOne("AccountingSystem.Data.Debit_Accounts", "Debit")
                        .WithMany()
                        .HasForeignKey("debitId");

                    b.Navigation("Credit");

                    b.Navigation("Debit");
                });

            modelBuilder.Entity("AccountingSystem.Data.Credited_Accounts", b =>
                {
                    b.HasOne("AccountingSystem.Data.Account_List", "AccName")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.Navigation("AccName");
                });

            modelBuilder.Entity("AccountingSystem.Data.Debit_Accounts", b =>
                {
                    b.HasOne("AccountingSystem.Data.Account_List", "AccName")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.Navigation("AccName");
                });

            modelBuilder.Entity("AccountingSystem.Data.Journal_Entry", b =>
                {
                    b.HasOne("AccountingSystem.Data.Account_List", "AccName")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("AccountingSystem.Data.Credited_Accounts", "Credit")
                        .WithMany()
                        .HasForeignKey("creditId");

                    b.HasOne("AccountingSystem.Data.Debit_Accounts", "Debit")
                        .WithMany()
                        .HasForeignKey("debitId");

                    b.Navigation("AccName");

                    b.Navigation("Credit");

                    b.Navigation("Debit");
                });

            modelBuilder.Entity("AccountingSystem.Data.Trial_Balance", b =>
                {
                    b.HasOne("AccountingSystem.Data.Account_List", "AccName")
                        .WithMany()
                        .HasForeignKey("accountId");

                    b.HasOne("AccountingSystem.Data.Amount", "Amount")
                        .WithMany()
                        .HasForeignKey("amountId");

                    b.HasOne("AccountingSystem.Data.Group_List", "AccGrp")
                        .WithMany()
                        .HasForeignKey("groupId");

                    b.Navigation("AccGrp");

                    b.Navigation("AccName");

                    b.Navigation("Amount");
                });
#pragma warning restore 612, 618
        }
    }
}
